name: Build project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Install Dependencies
        run: dotnet restore ./Mako/Mako.sln

      - name: Build Project
        run: dotnet build ./Mako/Mako.sln --configuration Release

      - name: Publish Project
        run: dotnet publish ./Mako/Mako.csproj -c Release -o ./output

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/wwwroot
